import well1 from '../images/1.well-steed-1.jpg';
import well2 from '../images/2.well-fukashils-1.jpg';
import well3 from '../images/3.well-supplybowling-1.jpg';
import well4 from '../images/4.well-limitlessblack-1.jpg';
import well5 from '../images/5.well-boardshort-1.jpg';
import well6 from '../images/6.well-heartblack-1.jpg';
import well7 from '../images/7.well-spectrum-black-1.jpg';
import well8 from '../images/8.well-evadecrease-1.jpg';
import well9 from '../images/9.well-canate-1.jpg';
import well10 from '../images/10.well-creaseebony-1.jpg';
import well11 from '../images/11.hoo-paisley-1.jpg';
import well12 from '../images/12.hoo-burtonifwt-1.jpg';
import well13 from '../images/13.hoo-terrain-1.jpg';
import well14 from '../images/14.hoo-awayday-1.jpg';
import well15 from '../images/15.hoo-legendshirt-1.jpg';
import well16 from '../images/16.hoo-canto-1.jpg';
import well17 from '../images/17.hoo-academia-1.jpg';
import well18 from '../images/18.hoo-woodgate-1.jpg';
import well19 from '../images/19.hoo-burton-maroon-1.jpg';
import well20 from '../images/20.hoo-linea-1.jpg';
export const data = [
    {
      id: 1,
      imageSrc: well1,
      name: "Steed LS T-shirt",
      company: 'Wellborncompany',
      content: "-",
      price: 265000,
      rating: 5,
      reviews: 87,
      category: 'baju',
      color: ['black'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 2,
      imageSrc: well2,
      name: "Fukasi LS",
      company: 'Wellborncompany',
      content: "-",
      price: 225000,
      rating: 4,
      reviews: 34,
      category: 'baju',
      color: ['white-black'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 3,
      imageSrc: well3,
      name: "Supply Bowling",
      company: 'Wellborncompany',
      content: "-",
      price: 345000,
      rating: 3,
      reviews: 26,
      category: 'kemeja',
      color: ['green'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id:4,
      imageSrc: well4,
      name: "Limitless T-shirt",
      company: "Wellborncompany",
      price: 24500,
      rating: 4,
      reviews: 95,
      category: 'baju',
      color: ['black'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'ts'
    },
    {
      id: 5,
      imageSrc: well5,
      name: "Bordshort Obdisian",
      company: "Wellborncompany",
      price: 225000,
      rating: 5,
      reviews: 61,
      category: 'celana',
      color: ['black'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 6,
      imageSrc: well6,
      name: "Heart shirt",
      company: "Wellborncompany",
      price: 245000,
      rating: 4,
      reviews: 89,
      category: 'baju',
      color: ['black'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 7,
      imageSrc: well7,
      name: "Spectrum Dark Jacket",
      company: "Wellborncompany",
      price: 500000,
      rating: 4,
      reviews: 12,
      category: 'jaket',
      color: ['dark-army'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 8,
      imageSrc: well8,
      name: "Evade Crease Long Pants",
      company: "Wellborncompany",
      price: 385000,
      rating: 4,
      reviews: 19,
      category: 'celana',
      color: ['olive'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 9,
      imageSrc: well9,
      name: "Canate Boxy Shirt Black",
      company: "Wellborncompany",
      price: 245000,
      rating: 4,
      reviews: 19,
      category: 'kemeja',
      color: ['black'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 10,
      imageSrc: well10,
      name: "Crease Cargo Ebony",
      company: "Wellborncompany",
      price: 425000,
      rating: 4,
      reviews: 19,
      category: 'celana',
      color: ['olive'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 11,
      imageSrc: well11,
      name: "Paisley Tee",
      company: "Hooligans12th",
      price: 76000,
      rating: 4,
      reviews: 13,
      category: 'baju',
      color: ['black'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 12,
      imageSrc: well12,
      name: "Burton IFWT",
      company: "Hooligans12th",
      price: 99000,
      rating: 4,
      reviews: 36,
      category: 'celana',
      color: ['dark-blue'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 13,
      imageSrc: well13,
      name: "Terrain SAU",
      company: "Hooligans12th",
      price: 69000,
      rating: 4,
      reviews: 30,
      category: 'baju',
      color: ['black'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 14,
      imageSrc: well14,
      name: "Awaydays 20-Tee",
      company: "Hooligans12th",
      price: 69000,
      rating: 4,
      reviews: 31,
      category: 'baju',
      color: ['white'],
      url: "#",
      shipping: true,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 15,
      imageSrc: well15,
      name: "Unknown-Tee",
      company: "Hooligans12th",
      price: 79000,
      rating: 4,
      reviews: 34,
      category: 'baju',
      color: ['black'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 16,
      imageSrc: well16,
      name: "Canto Crewneck",
      company: "Hooligans12th",
      price: 159000,
      rating: 4,
      reviews: 34,
      category: 'jaket',
      color: ['black'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 17,
      imageSrc: well17,
      name: "Academia 20.1",
      company: "Hooligans12th",
      price: 69000,
      rating: 4,
      reviews: 35,
      category: 'celana',
      color: ['gray'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 18,
      imageSrc: well18,
      name: "Woodgate",
      company: "Hooligans12th",
      price: 198000,
      rating: 4,
      reviews: 30,
      category: 'jaket',
      color: ['black'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 19,
      imageSrc: well19,
      name: "Burton 20.5 Maroon Boardshort",
      company: "Hooligans12th",
      price: 124000,
      rating: 4,
      reviews: 20,
      category: 'celana',
      color: ['maroon'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    },
    {
      id: 20,
      imageSrc: well20,
      name: "Linea",
      company: "Hooligans12th",
      price: 124000,
      rating: 4,
      reviews: 20,
      category: 'celana',
      color: ['maroon'],
      url: "#",
      shipping: false,
      stock: 10,
      description: 'testing satu dua tiga'
    }
  ]